### ISSUE TITLE
Error: Can't pickle local object 'ProxmoxBMCManager._sync_pbmc_states.<locals>.pbmc_runner'

### ISSUE THREAD

**Issue by fahadysf** [agnon/proxmoxbmc#3]
With a single instance configured I get this error:

`2023-02-27 20:11:35,711 75732 ERROR ProxmoxBMC [-] Can't pickle local object 'ProxmoxBMCManager._sync_pbmc_states.<locals>.pbmc_runner'`

I attempted to debug it and came accross this similar issue around multiprocessing and ability to serialize/pickle local objects but can't seem to understand where / how to tinker to fix it.

[https://stackoverflow.com/questions/60116458/multiprocessing-pool-map-attributeerror-cant-pickle-local-object](https://stackoverflow.com/questions/60116458/multiprocessing-pool-map-attributeerror-cant-pickle-local-object)

I did manage to get a full traceback of what's happening (by raising it in the pbmcd command):
```
Traceback (most recent call last):
  File "/Users/fahad/Code/proxmoxbmc/proxmoxbmc/cmd/pbmcd.py", line 97, in <module>
    sys.exit(main())
  File "/Users/fahad/Code/proxmoxbmc/proxmoxbmc/cmd/pbmcd.py", line 86, in main
    return wrap_with_pidfile(control.application, os.getpid())
  File "/Users/fahad/Code/proxmoxbmc/proxmoxbmc/cmd/pbmcd.py", line 71, in wrap_with_pidfile
    func()
  File "/Users/fahad/.pyenv/versions/py3.10.10/lib/python3.10/site-packages/proxmoxbmc/control.py", line 207, in application
    pbmc_manager.periodic()
  File "/Users/fahad/.pyenv/versions/py3.10.10/lib/python3.10/site-packages/proxmoxbmc/manager.py", line 231, in periodic
    self._sync_pbmc_states(shutdown)
  File "/Users/fahad/.pyenv/versions/py3.10.10/lib/python3.10/site-packages/proxmoxbmc/manager.py", line 182, in _sync_pbmc_states
    instance.start()
  File "/usr/local/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/local/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/local/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/context.py", line 288, in _Popen
    return Popen(process_obj)
  File "/usr/local/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/usr/local/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/local/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/usr/local/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'ProxmoxBMCManager._sync_pbmc_states.<locals>.pbmc_runner'
```

**Comment by fahadysf** [comment]
OK this is obscure and is only happening on MacOS with Python 3.10.10.. On Ubuntu 20.04 with python3.8 it is working fine.
